apiVersion: v1
kind: ResourceQuota
metadata:
  name: calico-demo-quota
  namespace: calico-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
    pods: "20"
