apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-5-quota
  namespace: project-5
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "30"
    persistentvolumeclaims: "5"
    services: "10"
