apiVersion: v1
kind: ResourceQuota
metadata:
  name: cilium-demo-quota
  namespace: cilium-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cilium-demo-limits
  namespace: cilium-demo
spec:
  limits:
  - max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 32Mi
    default:
      cpu: 200m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    type: Container
